config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/signup' => 'users#new'
  resources :users

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/about' => 'static_pages#about'
  get '/contact' => 'static_pages#contact'
  get '/help' => 'static_pages#help'

  resources :records, only:[:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc)}
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord

  has_many :records, dependent: :destroy
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name, {presence: true, length: {maximum: 50}}
  validates :email, {presence: true}
  has_secure_password
  validates :password, {presence: true, length: {minimum: 6}}

  include Gravtastic
  gravtastic
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private
   def logged_in_user
     unless logged_in?
         flash[:danger] = "Please Log in."
        redirect_to login_url
      end
    end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :logged_in_user, only:[:create, :destroy]

  def create
    @record = current_user.records.build(record_params)
    if @record.save
      flash[:success] = "created!"
      redirect_to root_url
    else
      render 'static_pages/home'
    end
  end

  def destroy
  end

  private
    def record_params
      params.require(:record).permit(:content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @record = current_user.records.build if logged_in?
  end

  def about
  end

  def contact
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only:[:index, :edit, :update, :destroy]
  before_action :correct_user, only:[:edit, :update]
  before_action :admin_user, only: :destroy

  def show
    @user = User.find(params[:id])
    @records = @user.records.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def index
    @users =User.paginate(page: params[:page], per_page: 10)
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please Log in."
        redirect_to login_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless @user == current_user
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user?(user)
    user == current_user
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options ={size:80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small> by riy0 </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Auto Dictator", 'root_path', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   '#' %></li>
        <li><%= link_to "About",   '#' %></li>

        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          aa
          <li class="dropdown">
            bb
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Account <b class="caret"></b> </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Edit", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to "Log out", logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AutoDictation</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/records/_record.html.erb
<li id="record-<%= record.id %>">
  <%= link_to gravatar_for(record.user, size: 50), record.user %>
  <span class="user"><%= link_to record.user.name , record.user %></span>
  <span class="content"><%= record.content %></span>
  <span class="timestamp">Posted <%= time_ago_in_words(record.created_at) %></span>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_record_form.html.erb
<div class="field">
  <textarea id="result_text" cols="100" rows="10"></textarea>
  <label id="status"></label>
</div>
  <input type="button" onClick="vr_function();" value="音認開始">

<script>
    var flag_speech = 0;
    function vr_function() {
        window.SpeechRecognition = window.SpeechRecognition || webkitSpeechRecognition;
        var recognition = new webkitSpeechRecognition();
        recognition.lang = 'ja';
        recognition.interimResults = true;
        recognition.continuous = true;
        recognition.onsoundstart = function() {
            document.getElementById('status').innerHTML = "認識中";
        };
        recognition.onnomatch = function() {
            document.getElementById('status').innerHTML = "もう一度試してください";
        };
        recognition.onerror = function() {
            document.getElementById('status').innerHTML = "エラー";
            if(flag_speech == 0)
              vr_function();
        };
        recognition.onsoundend = function() {
            document.getElementById('status').innerHTML = "停止中";
              vr_function();
        };
        recognition.onresult = function(event) {
            var results = event.results;
            for (var i = event.resultIndex; i < results.length; i++) {
                if (results[i].isFinal)
                {
                    document.getElementById('result_text').innerHTML = results[i][0].transcript;
                    // console.log(results[i][0].transcript);
                    $('ul#voice-content').append('<li>' + results[i][0].transcript +'</li>')
                    var list = $("#voice-content li").text();
                    console.log(list);
                    document.getElementById('record_content').innerHTML = list;
                    flag_speech = 0;
                    vr_function();
                }
                else
                {
                    document.getElementById('result_text').innerHTML = "[途中経過] " + results[i][0].transcript;
                    flag_speech = 1;
                }
            }
        }
        flag_speech = 0;
        document.getElementById('status').innerHTML = "start";
        recognition.start();
    }
</script>

app/views/shared/_record_post.html.erb
<%= form_for(@record) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder:"New Content..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size:50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.records.count, "record") %></span>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Auto Dictator</h1>
  <% if logged_in? %>
    <div class="row">
      <aside class="col-md-4">
        <section class="user_info">
          <%= render "shared/user_info" %>
        </section>
        <section class="note_form">
          <%= render "shared/record_form" %>
        </section>
      </aside>
      <div class="col-md-8">
          <ul id="voice-content"> </ul>
      </div>
      <%= render "shared/record_post" %>
    </div>
  <% else %>
    <div class="center jumbotron">
      <h1>Auto Dictator</h1>
      <%= link_to "Sign up now!", signup_path , class: "btn btn-lg btn-primary" %>
    </div>
  <% end %>
</div>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete, data: {confirm: "You sure?"} %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <% f.label :name %>
      <%= f.text_field :name, class:'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class:'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class:'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class:'form-control' %>

      <%= f.submit "Save changes", class:"btn btn-primary" %>
    <% end %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sing Up') %>

<div class="row">
  <h1>Sign up</h1>
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name  %>
      <%= f.text_field :name, class:'form-control' %>

      <%= f.label :email  %>
      <%= f.email_field :email, class:'form-control' %>

      <%= f.label :password  %>
      <%= f.password_field :password, class:'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class:'form-control' %>

      <%= f.submit "Create my account", class:"btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="container">
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <h1>
          <%= gravatar_for @user %>
          <%= @user.name %>
        </h1>
      </section>
    </aside>
    <div class="col-md-8">
      <% if @user.records.any? %>
        <h3>Records (<%= @user.records.count %>)</h3>
        <ol class="records">
          <%= render @records%>
        </ol>
        <%= will_paginate @records%>
      <% end %>
    </div>
  </div>
</div>